#!/usr/bin/bash

# Configuration parameters for ECLIPSE
export HOST_NAME="localhost"
export HOST_IP="127.0.0.1"
export DB_NAME="eclipse"
export USER_NAME="postgres"
export PASSWORD="postgres"
export PGPASSWORD=${PASSWORD}  # posgresdb environment variable (do not change).

# --
